FROM node:18.2-alpine3.15 AS BUILDER
WORKDIR /workspace
COPY --chown=node:node ["package.json", "package-lock.json*", "yarn.lock*", "./"]
RUN yarn install

FROM node:18.2-alpine3.15
WORKDIR /workspace
COPY --from=BUILDER --chown=node:node /workspace .
COPY --chown=node:node . .
USER node
CMD ["yarn","dev"]