export const EVAL_CONDITION = {
  USER_LOGGED_IN: "USER_LOGGED_IN",
  USER_NOT_LOGGED_IN: "USER_NOT_LOGGED_IN",
  KYC_IS_COMPLETE: "KYC_IS_COMPLETE",
  KYC_NOT_COMPLETE: "KYC_NOT_COMPLETE",
} as const;

export const GROWW_URL = process.env.GROWW_URL;
