services:
  groww-fe:
    container_name: groww-fe
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /workspace/node_modules
      - .:/workspace
    ports:
      - "3000:3000"
    environment:
      - NEXT_APP_API_URL
    